spring:
  #data for database connection
  datasource:
    url: jdbc:postgresql://localhost:5432/telros_db
    username: postgres
    password: postgres
  jpa:
    generate-ddl: true
  #File configurations
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# variables
default:
  username: admin
  password: admin
secret: 335d3fab5ad1d4c9a1a2e3b78199cfc8ca8efd0f34757b97aff5ee5f99ee4544




